import { NextRequest, NextResponse } from 'next/server'
import { validateToken, requireRole } from '@/lib/auth/validateToken'
import { prisma } from '@/lib/db/prisma'
import * as XLSX from 'xlsx'

export async function GET(req: NextRequest) {
  const token = await validateToken(req)
  requireRole(token, ['HR'])

  const { searchParams } = new URL(req.url)
  const format = (searchParams.get('format') ?? 'xlsx').toLowerCase()

  if (!['xlsx', 'csv', 'pdf'].includes(format)) {
    return NextResponse.json({ error: 'format must be xlsx, csv, or pdf' }, { status: 400 })
  }

  const employees = await prisma.employee.findMany({
    where: { employmentStatus: { not: 'TERMINATED' } },
    include: {
      manager:      { select: { displayName: true, workEmail: true } },
      leaveBalance: true,
    },
    orderBy: { firstName: 'asc' },
  })

  const rows = employees.map(emp => ({
    'Azure Object ID':        emp.entraObjectId,
    'Display Name':           emp.displayName,
    'First Name':             emp.firstName,
    'Last Name':              emp.lastName,
    'Email':                  emp.workEmail,
    'Notification Email':     emp.notificationEmail  ?? '',
    'Job Title':              emp.jobTitle          ?? '',
    'Role':                   emp.role,
    'Employment Status':      emp.employmentStatus,
    'Phone Number':           emp.phoneNumber        ?? '',
    'Emergency Contact Name': (emp as any).emergencyName     ?? '',
    'Emergency Relation':     (emp as any).emergencyRelation ?? '',
    'Emergency Phone':        (emp as any).emergencyPhone    ?? '',
    'Manager Name':           emp.manager?.displayName ?? '',
    'Manager Email':          emp.manager?.workEmail       ?? '',
    'Join Date':              emp.joinDate
                                ? new Date(emp.joinDate).toLocaleDateString('en-IN')
                                : '',
    'Standard Leave Total':   emp.leaveBalance?.standardTotal  ?? 18,
    'Standard Leave Used':    emp.leaveBalance?.standardUsed   ?? 0,
    'Floater Leave Total':    emp.leaveBalance?.floaterTotal   ?? 2,
    'Floater Leave Used':     emp.leaveBalance?.floaterUsed    ?? 0,
    'Emergency Leave Total':  emp.leaveBalance?.emergencyTotal ?? 2,
    'Emergency Leave Used':   emp.leaveBalance?.emergencyUsed  ?? 0,
  }))

  const filename = `employees_${new Date().toISOString().split('T')[0]}`

  // ── XLSX / CSV ──────────────────────────────────────────────────────────────
  if (format === 'xlsx' || format === 'csv') {
    const ws = XLSX.utils.json_to_sheet(rows)

    // Auto-size columns
    const colWidths = Object.keys(rows[0] ?? {}).map(key => ({
      wch: Math.max(key.length, 15)
    }))
    ws['!cols'] = colWidths

    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'Employees')

    if (format === 'xlsx') {
      const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })
      return new NextResponse(buf, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'Content-Disposition': `attachment; filename="${filename}.xlsx"`,
        },
      })
    } else {
      const csv = XLSX.utils.sheet_to_csv(ws)
      return new NextResponse(csv, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="${filename}.csv"`,
        },
      })
    }
  }

  // ── PDF ─────────────────────────────────────────────────────────────────────
  if (format === 'pdf') {
    // Build a simple HTML table and return it as an HTML file the browser can print-to-PDF
    // (Avoids server-side PDF dependencies — the user uses browser Print → Save as PDF)
    const tableRows = rows.map(row =>
      `<tr>${Object.values(row).map(v => `<td>${String(v).replace(/</g, '&lt;')}</td>`).join('')}</tr>`
    ).join('\n')

    const headers = Object.keys(rows[0] ?? {})
      .map(h => `<th>${h}</th>`).join('')

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Employee Export — ${filename}</title>
  <style>
    body { font-family: Segoe UI, Arial, sans-serif; font-size: 11px; margin: 24px; }
    h2 { color: #1e293b; margin-bottom: 16px; }
    table { border-collapse: collapse; width: 100%; }
    th { background: #6366f1; color: white; padding: 6px 8px; text-align: left; font-size: 10px; white-space: nowrap; }
    td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
    tr:nth-child(even) td { background: #f8fafc; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <h2>Employee Directory — ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</h2>
  <p style="color:#64748b;margin-bottom:16px;">Total: ${rows.length} employees · Generated by Monkstack HRM</p>
  <table>
    <thead><tr>${headers}</tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `inline; filename="${filename}.html"`,
      },
    })
  }

  return NextResponse.json({ error: 'Invalid format' }, { status: 400 })
}
